### PR TITLE
Add first pass at architectual source of truth for Autokit

### PR DESCRIPTION
**Pull request by anujdeshpande**
Change-type: patch

### CODE REVIEW

**Comment by anujdeshpande** [comment]
@rcooke-warwick @Bucknalla Some changes are needed to get a website built for your repo here.

- documentation folder was renamed as docs. Links in README for images in the folder were fixed as well
- Additional input was added to your flowzone.yml which passes the cloudflare pages project that was created for your repo (this is a manual process which will be done by ops in the future). This is a one time config, and you aren't expected to change that ever again (Changing that has the potential to cause very bad things too)
- For now, I am pointing to a branch of flowzone in this PR. That will change to master branch before I merge this PR in your repo (I am working on a review with the @ flowzone devs)

**Comment by Bucknalla** [comment]
Cool thanks @anujdeshpande

**Comment by Bucknalla** [comment]
Continuing the work here to add a first pass at explaining the AutoKit project and how the architecture of the software and hardware work together. This will exist as a docusaurus website now that is functional and act as a sign post for other documents such as the user guide, SDK docs and assembly instructions.

**Comment by rcooke-warwick** [comment]
imo, the key parts that should go in this doc are: 

- what is an autokit
- what is the purpose of the autokit
- the hardware architecture: including why USB
- the software architecture (at a high level - the details imo should go in the sw repo with the code, but we can include things like mentioning npm package + webserver, running tests on the autokit, or remotely etc
- pointers to the relevent repos [autokit-sw, assembly, user guide]
- remove the links to the "modules" that are currently there, there shouldn't be a pseudo BoM here imo

**Pull request closed without merging**
