### PR TITLE
add initial sw interface

### PR DESCRIPTION
**Pull request by rcooke-warwick**
Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
It's finally here 😇 I have some ideas on autokitSDK

**Comment by rcooke-warwick** [comment]
superseded by https://github.com/balena-io-hardware/autokit-sw/pull/1

**Comment by rcooke-warwick** [comment]
https://github.com/balena-io-hardware/autokit-sw/pull/1

**Pull request closed without merging**
